### ISSUE TITLE
SVGO Plugin Options

### ISSUE THREAD

**Issue by solidevolution** [e-e-e/rollup-plugin-vue-inline-svg#2]
Need to change SVGO Plugin options in configuration

Currently this plugin removes ids from imported svg's

**Comment by e-e-e** [comment]
Yep, I will see if i can expose those settings for you to configure to your own needs through rollup.

**Comment by e-e-e** [comment]
This commit allows you to pass through any config options you like to svgo - https://github.com/e-e-e/rollup-plugin-vue-inline-svg/commit/bd0491c68b8c6195f69b4d2f37e21a363a5e3a21. Let me know if you have any issues, I have not tested thoroughly.

**Comment by e-e-e** [comment]
From NPM just install version 1.0.1

**Comment by solidevolution** [comment]
Big thx, this works now!

Further I've got my problems with svgo plugin configuration, so i'm not sure if this is the best way if you have to import a big svg with ids and classes which you would transform with Vue and/or GSAP. 

Currently we only have a really simple svg with a lot of paths but only 4 classes and 6 ids to Tween with GSAP. If I import it with svgo, it doesn't work anymore. Didn't understand why the default config transform the svg extremly. 

I try to deactivate every svgo plugin ... or search another solution like html import ;)

**Comment by e-e-e** [comment]
No problem at all.

My understanding is that it svgo optimises the svg to minimise bundling size. I would recommend looking at the resulting transpiled code. Its hard for me to offer much in way of suggestion without seeing code samples. Even then perhaps stackoverflow is a better source of advice as you will catch more experienced eyes.

**Comment by solidevolution** [comment]
Of course, you're working is done. Thank you!
