### ISSUE TITLE
Publish new version on npm

### ISSUE THREAD

**Issue by przemkow** [e-e-e/rollup-plugin-vue-inline-svg#7]
Hi! 
At first, I would like to thank you for the amazing work!
I see that this PR https://github.com/e-e-e/rollup-plugin-vue-inline-svg/pull/5 was merged 3 months ago but this version is not present yet on NPM.
https://www.npmjs.com/package/rollup-plugin-vue-inline-svg

Would it be possible to run `npm publish` so we can fetch the newest version directly from npm?

**Comment by e-e-e** [comment]
Apologies for taking so long to do this. I have not been working with vue for a while so maintaining this library has been low priority.

**Comment by e-e-e** [comment]
New version has been released.
