### ISSUE TITLE
How to use both inline and external SVGs?

### ISSUE THREAD

**Issue by abdulmlik** [e-e-e/rollup-plugin-vue-inline-svg#8]
How to use both inline and external SVGs?
I have checked the doc svgo But I did not find anything to help me

https://vue-svg-loader.js.org/faq.html#how-to-use-both-inline-and-external-svgs

**Comment by e-e-e** [comment]
The documentation you link to is for webpack. This plugin is intended for rollup and at the moment only supports inline svg.
It should not be too difficult to configure rollup to reference specific svgs to be loaded as external resources, but unfortunately I am unable to help with that. Perhaps consult the rollup docs.
