### ISSUE TITLE
Invalid Component definition

### ISSUE THREAD

**Issue by nataliawww** [e-e-e/rollup-plugin-vue-inline-svg#9]
Getting this error trying to import any svg files in Vue 2

**Comment by e-e-e** [comment]
Does it work with an earlier version of this library - could you try 1.1.1?
Also what version of Vue 2 are you running?

**Comment by vish01** [comment]
Is there a way to make this package work for Vue 3? When I try to use it in Vue version 3.0.7, I get this error message:
Vue packages version mismatch:

- vue@3.0.7 (C:\Users\myFolder\node_modules\vue\index.js)
- vue-template-compiler@2.6.12 (C:\Users\myFolder\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by e-e-e** [comment]
I am closing this issue and opening a new one specifically about Vue 3 compatibility to make this issue a bit more visible - see https://github.com/e-e-e/rollup-plugin-vue-inline-svg/issues/10.
I will see what I can do - I am not actively developing with Vue at the moment so it might take me a little bit of time to address. PRs are very welcome - it might be as simple as updating the vue dependencies - if you feel like having a go at fixing this.
